ARDUINO_VARIANT = esp32c6
SERIAL_PORT = /dev/ttyACM1
# uncomment and set the right serail baud according to your sketch (default to 115200)
#SERIAL_BAUD = 115200
# uncomment this to use the 1M SPIFFS mapping
#SPIFFS_SIZE = 1
#ESP8266_VERSION=git
CONCATENATE_USER_FILES=no
ARDUINO_LIBS=NetworkClientSecure Network
OTA_IP = 192.168.1.184
OTA_PORT = 8266 
OTA_AUTH = password
include ../../../esp32Arduino.mk

