ARDUINO_VARIANT = nodemcu
SERIAL_PORT = /dev/nodemcu
# uncomment and set the right serail baud according to your sketch (default to 115200)
#SERIAL_BAUD = 115200
ESP8266_VERSION=.git
include ../../../espXArduino.mk

