ARDUINO_VARIANT = nodemcu
SERIAL_PORT = /dev/nodemcu
# uncomment and set the right serail baud according to your sketch (default to 115200)
#SERIAL_BAUD = 115200
# uncomment this to use the 1M SPIFFS mapping
#SPIFFS_SIZE = 1
include ../../../espXArduino.mk

