ARDUINO_VARIANT = nodemcu
SERIAL_PORT = /dev/nodemcu
# uncomment and set the right serial baud according to your sketch (default to 115200)
#SERIAL_BAUD = 115200
ESP8266_VERSION=.git
LOG_SERIAL_TO_FILE=yes
USER_DEFINE = -D_SSID_=\"YourSSID\" -D_WIFI_PASSWORD_=\"YourPassword\"
OTA_IP = 192.168.1.184
OTA_PORT = 8266 
OTA_AUTH = password
include ../../../espXArduino.mk

