ARDUINO_VARIANT    = generic
SERIAL_PORT = /dev/ttyUSB0

FLASH_SIZE=1M
FLASH_FREQ=40MHz
FLASH_LD=eagle.flash.1m64.ld
USER_DEFINE = -D_SSID_=\"YourSSID\" -D_WIFI_PASSWORD_=\"YourPassword\"
OTA_IP = 192.168.1.184
OTA_PORT = 8266 
OTA_AUTH = password
include ../../../espXArduino.mk
