ARDUINO_VARIANT = nodemcuv2
SERIAL_PORT = /dev/ttyUSB0
# uncomment and set the right serial baud according to your sketch (default to 115200)
#SERIAL_BAUD = 115200
LOG_SERIAL_TO_FILE=yes
ESP8266_VERSION=git
USER_DEFINE = -D_SSID_=\"YourSSID\" -D_WIFI_PASSWORD_=\"YourPassword\"
OTA_IP = 192.168.1.184
OTA_PORT = 8266 
OTA_AUTH = password
include ../../../esp8266Arduino.mk

