ARDUINO_VARIANT    = generic
SERIAL_PORT = /dev/ttyUSB0
#ESP8266_VERSION=.git
USER_DEFINE = -D_SSID_=\"YourSSID\" -D_WIFI_PASSWORD_=\"YourPassword\"
OTA_IP = 192.168.1.184
OTA_PORT = 8266 
OTA_AUTH = password
include ../../../espXArduino.mk
