ARDUINO_VARIANT = lolin32
SERIAL_PORT = /dev/ttyUSB1
# uncomment and set the right serail baud according to your sketch (default to 115200)
#SERIAL_BAUD = 115200
# uncomment this to use the 1M SPIFFS mapping
#SPIFFS_SIZE = 1
#ESPXX_VERSION=git
ARDUINO_ARCH=esp32
USER_DEFINE = -D_SSID_=\"YourSSID\" -D_WIFI_PASSWORD_=\"YourPassword\"
OTA_IP = 192.168.1.184
OTA_PORT = 8266 
OTA_AUTH = password
include ../../../espXArduino.mk

